### ISSUE TITLE
no icon

### ISSUE THREAD

**Issue by axel05869** [simrat39/AnimeTwistFlut#13]
Does the app doesnt have an icon or it is just me?

**Comment by simrat39** [comment]
![Screenshot_20210123-093838_ArrowOS_Launcher.png](https://user-images.githubusercontent.com/37233846/105609540-e1b55b00-5d5e-11eb-8213-abf17043e463.png)
There definitely is an icon present

**Comment by axel05869** [comment]
![Uploading 20210124_063932.png…]()
oh, nevermind. Maybe it's just my phone
btw. Im using the armeabi-v7a version.
