### ISSUE TITLE
External player

### ISSUE THREAD

**Issue by ThePurpleApple** [simrat39/AnimeTwistFlut#17]
Could you please add support for external players such as mx player. This app works really well and even on android tv apart from being able to use the integrated player.

Thank you

**Comment by simrat39** [comment]
![](https://i.imgur.com/Kyxe8lB.jpg)

**Comment by simrat39** [comment]
Will only work with mx player for now but itll be available in the next release

**Comment by ThePurpleApple** [comment]
That's perfect as mx player is what is really the only one I use and seems to be the most used, thank you for your work!

**Comment by hazre** [comment]
vlc would be cool too

**Comment by simrat39** [comment]
> vlc would be cool too

I'm trying to find a way but it seems like VLC straight up does not like headers, while MxPlayer has an API for it.

![image](https://user-images.githubusercontent.com/37233846/109434938-8402d700-79cc-11eb-9dc7-37f2642f2769.png)

**Comment by hazre** [comment]
Alright, also I just checked your commits and looks like you forgot about the pro version package `com.mxtech.videoplayer.pro`

**Comment by tanaypatankar** [comment]
You could fire an intent when the play button is tapped You would need to pass the URL. You won't have to worry about individual applications.

import 'package:android_intent/android_intent.dart';
import 'package:android_intent/flag.dart';

.........

final AndroidIntent intent = AndroidIntent(
  action: 'action_view',
  data: Uri.encodeFull(streamURL),
  flags: <int>[Flag.FLAG_ACTIVITY_NEW_TASK],
);
intent.launch();

**Comment by simrat39** [comment]
@tanaypatankar Twist's cdn needs a few headers to be passed or else the video does not stream, and there is not a set api to send headers with intents, different apps get them from different ways, hence I have to alienate the code to different apps.

**Comment by xyse** [comment]
@simrat39 Sorry, but I don't seem to find an option to play a video in mx player? Could you elaborate on how to do that. Seems to be working for you.

**Comment by simrat39** [comment]
@xyse it will be possible in the next release.

**Comment by simrat39** [comment]
Added in latest release.
https://github.com/simrat39/AnimeTwistFlut/releases/tag/7.0.0
