### ISSUE TITLE
The video page is not working

### ISSUE THREAD

**Issue by dheerajbred** [simrat39/AnimeTwistFlut#4]
When I click on the episode it says

![image](https://user-images.githubusercontent.com/46578244/97786210-27cfa800-1bd0-11eb-9137-3faf9393f411.png)

**Comment by simrat39** [comment]
Did you compile the app yourself? Because you need to provide a decryption key while building (Check readme) which you can get from the AnimeTwist team. You can download a prebuilt working apk from here - https://github.com/simrat39/AnimeTwistFlut/releases

**Comment by simrat39** [comment]
Anyways, 5befff926372393950ad5e1c3dbb747b4edd2990 handles it.
