### ISSUE TITLE
Suggestion. 

### ISSUE THREAD

**Issue by PrathamModi69** [simrat39/AnimeTwistFlut#8]
I really like the app and have been using it for a while now. I was wondering if the forward and backward could be 5 sec instead of 10 because I only use it when I miss a moment or miss the subtitles so a 10sec becomes a stretch. Are there any cons to having 5 sec if so can you tell them? Thanks for the hard work.

**Comment by simrat39** [comment]
> I really like the app and have been using it for a while now. I was wondering if the forward and backward could be 5 sec instead of 10 because I only use it when I miss a moment or miss the subtitles so a 10sec becomes a stretch. Are there any cons to having 5 sec if so can you tell them? Thanks for the hard work.

Honestly i was just copying Youtube, it could be 5 seconds and that would be fine too. Maybe a setting for it would make more sense than one arbitrary value.

**Comment by PrathamModi69** [comment]
> > I really like the app and have been using it for a while now. I was wondering if the forward and backward could be 5 sec instead of 10 because I only use it when I miss a moment or miss the subtitles so a 10sec becomes a stretch. Are there any cons to having 5 sec if so can you tell them? Thanks for the hard work.
> 
> Honestly i was just copying Youtube, it could be 5 seconds and that would be fine too. Maybe a setting for it would make more sense than one arbitrary value.

That would be epic.

**Comment by simrat39** [comment]
I'll do it tomorrow

**Comment by PrathamModi69** [comment]
Also sorry I forgot to ask about another thing. Is it possible for the episode to go landscape automatically instead of using the button that would be a bit convenient.

**Comment by simrat39** [comment]
@PrathamModi69 Yes that is in my todo, will do that soon as well
