### ISSUE TITLE
Android TV compatibility

### ISSUE THREAD

**Issue by marinosGR** [simrat39/AnimeTwistFlut#9]
The app navigation seems to work correctly but it doesn't respond to selection. Also it needs some declarations to AndroidManifest.xml for the app to appear at the launcher.

Some information can be found here
https://developer.nvidia.com/android-tv-deployment-checklist

and here
https://developer.nvidia.com/android-tv-developer-guide#leanback_intent

I tried the release which included the commit  0c6c8d0
app-armeabi-v7a-release.apk

**Comment by simrat39** [comment]
https://medium.com/@pcmushthaq/adding-android-tv-support-to-your-flutter-app-dcc5c1196231

Shouldn't be that hard, I just need to make a banner.
Improvements for landscape mode will come in the future.
